
import os
print("Ciao!, Benvenuto nel mio bar.")
input("(premi un tasto...)")
os.system('cls')
print("Presentati pure, come ti chiami?")
nome = input()
os.system('cls')
print("Ciao", nome, "piacere di conoscerti.")
input("(premi un tasto...)")
os.system('cls')
print("Che cosa desideri prendere?")
bevanda = input()
os.system('cls')
print("Va bene,", nome, "una", bevanda, "in arrivo.")
input("(premi un tasto...)")
os.system('cls')
print("...")
input("(premi un tasto...)")
os.system('cls')
print("...")
input("(premi un tasto...)")
os.system('cls')
print("Allora..., sono andato in magazzino a prendere la tua bevanda...")
input("(premi un tasto...)")
os.system('cls')
print("Ma quel frocio di Tonella si è fottuto tutto")
input("(premi un tasto...)")
os.system('cls')
input("[Dici qualcosa]: ")
os.system('cls')
print("Ma non ti preoccupare,", nome, "ho un piano B.")
os.system('cls')
input("(premi un tasto...)")
os.system('cls')
print("Ora prendo un cazzo di lanciafiamme e lo brucio quel figlio di puttana.")
input("(premi un tasto...)")
os.system('cls')
print("Passami la bombola del gas")
input("(premi un tasto...)")
os.system('cls')
print("OPZIONI: 1. Bombola del gas 2.",bevanda, "3. Pistola")
opzione = input("[Scegli un'opzione]: ")
os.system('cls')
if opzione == "1":
    print("Grazie bro, andiamo a bruciare quel pesce")
elif opzione == "2":
    print("Che cazzo vuoi fare con una", bevanda, "?")
elif opzione == "3":
    print("Che cazzo vuoi fare con una pistola? Quella e' utile contro i nani")
os.system('cls')
print("e' finita per te Tonella!")
input("(premi un tasto...)")
os.system('cls')
print("TONELLA: BLEBLEBLEBLE")
input("(premi un tasto...)")
os.system('cls')
print("Oddio e' pure scemo, porro' fine alle sue sofferenze")
input("(premi un tasto...)")
os.system('cls')
print("va bene,", nome, "la tua", bevanda, "sta per arrivare")
input("(premi un tasto...)")
os.system('cls')
print("Ecco a te. Com'e?")
input("(premi un tasto...)")
os.system('cls')



